# fly.toml app configuration file generated for crmserver on 2023-07-15T12:38:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crmserver"
primary_region = "ams"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_DEBUG = "true"
  APP_ENV = "production"
  APP_NAME = "Laravel"
  APP_URL = "https://crmserver.fly.dev"
  BROADCAST_DRIVER = "log"
  CACHE_DRIVER = "file"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "crmserver"
  DB_HOST = "aws.connect.psdb.cloud"
  DB_PASSWORD = "pscale_pw_RsVzischRuhphSmYRS6PaUixsul7VanapHxqGambFUn"
  DB_PORT = "3306"
  DB_USERNAME = "n5hkgtznzjdheeqys4eb"
  FILESYSTEM_DISK = "local"
  LOG_CHANNEL = "stderr"
  LOG_CHANNEL2 = "stderr"
  LOG_DEPRECATIONS_CHANNEL = "null"
  LOG_LEVEL = "info"
  LOG_LEVEL2 = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  LOG_STDERR_FORMATTER2 = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "tls"
  MAIL_FROM_ADDRESS = "cashboys14@example.com"
  MAIL_FROM_NAME = "${APP_NAME}"
  MAIL_HOST = "smtp.mailtrap.io"
  MAIL_MAILER = "smtp"
  MAIL_PASSWORD = "0202c5f15f994b"
  MAIL_PORT = "2525"
  MAIL_USERNAME = "a6fd851f4e63a0"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  QUEUE_CONNECTION = "sync"
  SESSION_DRIVER = "cookie"
  SESSION_DRIVER2 = "cookie"
  SESSION_LIFETIME = "120"
  SESSION_SECURE_COOKIE = "true"
  SESSION_SECURE_COOKIE2 = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
